spring.application.name=CBTa97Net

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:cbta97net}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=CBTa97-Pool

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

spring.jackson.mapper.accept-case-insensitive-enums=true

file.upload-dir=uploads

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KC_HOST:localhost}:${KC_PORT:9090}/realms/${KC_REALM_NAME:cbta97-realm-prod}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KC_HOST:localhost}:${KC_PORT:9090}/realms/${KC_REALM_NAME:cbta97-realm-prod}/protocol/openid-connect/certs
keycloak.server-url=http://${KC_HOST:localhost}:${KC_PORT:9090}
keycloak.realm=${KC_REALM_NAME:cbta97-realm-prod}
keycloak.client-id=${KC_CLIENT_ID:cbta97-client-api-rest}
keycloak.client-secret=${KC_CLIENT_SECRET:**********}
keycloak.realm-master=${KC_REALM_MASTER:master}
keycloak.admin-cli=${KC_ADMIN_CLI:admin-cli}
keycloak.user-console=${KC_USER_CONSOLE:superadmin}
keycloak.password-console=${KC_PASSWORD_CONSOLE:cbta19040042}
keycloak.client-secret-admin=${KC_CLIENT_SECRET_ADMIN:admin}

jwt.auth.converter.resource-id=cbta97-client-api-rest
jwt.auth.converter.principle-attribute=preferred_username
logging.level.org.keycloak = DEBUG

# SFTP
sftp.host=${SFTP_HOST:localhost}
sftp.port=${SFTP_PORT:2222}
sftp.user=${SFTP_USER:admin_sftp}
sftp.password=${SFTP_PASSWORD:secret123}
sftp.directory=

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:80,http://localhost,http://62.84.186.83:8080,http://62.84.186.83}

